name = "g2-middle-east-staging"
compatibility_date = "2024-11-19"
pages_build_output_dir = ".vercel/output/static"

# Cloudflare Pages configuration for Next.js
[build]
command = "npm run pages:build"

[env.production]
name = "g2-middle-east-production"

[env.preview]
name = "g2-middle-east-preview"
